[2024-06-07T15:19:43.274+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T15:19:43.285+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest manual__2024-06-07T15:19:39.107785+00:00 [queued]>
[2024-06-07T15:19:43.368+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest manual__2024-06-07T15:19:39.107785+00:00 [queued]>
[2024-06-07T15:19:43.369+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-07T15:19:43.374+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingest> on 2024-06-07 15:19:39.107785+00:00
[2024-06-07T15:19:43.377+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T15:19:43.378+0000] {standard_task_runner.py:63} INFO - Started process 82 to run task
[2024-06-07T15:19:43.378+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2024-06-07T15:19:39.107785+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpwpshg9zg']
[2024-06-07T15:19:43.379+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask ingest
[2024-06-07T15:19:43.398+0000] {task_command.py:426} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2024-06-07T15:19:39.107785+00:00 [running]> on host 2ffb2e6a8d81
[2024-06-07T15:19:43.418+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-06-07T15:19:43.432+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T15:19:39.107785+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-07T15:19:39.107785+00:00'
[2024-06-07T15:19:43.433+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T15:19:43.439+0000] {ingest_data.py:45} INFO - 2024-06-07 15:19:39.107785+00:00
[2024-06-07T15:19:43.441+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T15:19:43.441+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingest_data.py", line 51, in ingest_callable
    df_iter = pd.read_csv(csv_file, iterator=True, chunksize=100000)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1723, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 579, in pandas._libs.parsers.TextReader.__cinit__
  File "parsers.pyx", line 668, in pandas._libs.parsers.TextReader._get_header
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2050, in pandas._libs.parsers.raise_parser_error
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
[2024-06-07T15:19:43.446+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, run_id=manual__2024-06-07T15:19:39.107785+00:00, execution_date=20240607T151939, start_date=20240607T151943, end_date=20240607T151943
[2024-06-07T15:19:43.451+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task ingest ('utf-8' codec can't decode byte 0x8b in position 1: invalid start byte; 82)
[2024-06-07T15:19:43.478+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-07T15:19:43.486+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-07T15:19:43.487+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
